import type { SkillTreeDef } from './types'

// Matura z polskiego 2026 — przykładowy dataset
// Źródło lektur: CKE, lista obowiązkowa (formuła 2023)

const polskiMatura: SkillTreeDef = {
  id: 'polski-matura-2026',
  title: 'Matura z polskiego 2026',
  description: 'Pełne drzewo: epoki, lektury obowiązkowe, motywy, gatunki, warsztat, mosty międzyprzedmiotowe',

  branches: {
    epoki:    { label: 'Epoki',    color: '#f43f5e' },
    lektury:  { label: 'Lektury',  color: '#3b82f6' },
    motywy:   { label: 'Motywy',   color: '#a855f7' },
    gatunki:  { label: 'Gatunki',  color: '#22c55e' },
    warsztat: { label: 'Warsztat', color: '#06b6d4' },
    bridge:   { label: 'Most międzyprzedmiotowy', color: '#fbbf24' },
  },

  nodes: [
    // ── EPOKI (kręgosłup) ──
    { id: 'antyk',            title: 'Antyk',                   branch: 'epoki', tier: 0 },
    { id: 'sredniowiecze',   title: 'Średniowiecze',           branch: 'epoki', tier: 1 },
    { id: 'renesans',        title: 'Renesans',                branch: 'epoki', tier: 2 },
    { id: 'oswiecenie',      title: 'Oświecenie / Klasycyzm',  branch: 'epoki', tier: 3 },
    { id: 'romantyzm',       title: 'Romantyzm',               branch: 'epoki', tier: 4 },
    { id: 'pozytywizm',      title: 'Pozytywizm',              branch: 'epoki', tier: 5 },
    { id: 'modernizm',       title: 'Młoda Polska',            branch: 'epoki', tier: 6 },
    { id: 'dwudziestolecie', title: 'Dwudziestolecie',         branch: 'epoki', tier: 7 },
    { id: 'ii-wojna',        title: 'II wojna / Holocaust',    branch: 'epoki', tier: 8 },
    { id: 'wspolczesnosc',   title: 'Współczesność',           branch: 'epoki', tier: 9 },

    // ── LEKTURY: Antyk ──
    { id: 'biblia',       title: 'Biblia (fragmenty)',        branch: 'lektury', tier: 0,
      description: 'Księga Rodzaju, Hioba, Koheleta, Psalmów, Apokalipsa',
      terms: ['genesis', 'apokalipsa', 'przypowieść', 'psalm', 'vanitas', 'eschatologia'] },
    { id: 'mitologia',    title: 'Mitologia — Parandowski',   branch: 'lektury', tier: 0,
      terms: ['mit', 'archetyp', 'hybris', 'katharsis', 'Olimp', 'heros'] },
    { id: 'iliada',       title: 'Iliada — Homer (fr.)',      branch: 'lektury', tier: 0,
      terms: ['epos', 'inwokacja', 'heksametr', 'epitheton ornans', 'porównanie homeryckie'] },
    { id: 'antygona',     title: 'Antygona — Sofokles',       branch: 'lektury', tier: 0,
      terms: ['tragizm', 'hamartia', 'hybris', 'fatum', 'katharsis', 'chór', 'ironia tragiczna'] },

    // ── LEKTURY: Średniowiecze ──
    { id: 'lament',       title: 'Lament świętokrzyski',      branch: 'lektury', tier: 1,
      terms: ['planctus', 'compassio', 'liryka religijna'] },
    { id: 'polikarp',     title: 'Rozmowa Mistrza Polikarpa', branch: 'lektury', tier: 1,
      terms: ['danse macabre', 'memento mori', 'dialog', 'dydaktyzm'] },
    { id: 'roland',       title: 'Pieśń o Rolandzie (fr.)',   branch: 'lektury', tier: 1,
      terms: ['chanson de geste', 'etos rycerski', 'feudalizm', 'wasal'] },

    // ── LEKTURY: Renesans ──
    { id: 'makbet',       title: 'Makbet — Szekspir',         branch: 'lektury', tier: 2,
      terms: ['ambicja', 'monolog', 'solilokwium', 'makbetyzm', 'motyw winy'] },

    // ── LEKTURY: Oświecenie ──
    { id: 'skapiec',      title: 'Skąpiec — Molier',          branch: 'lektury', tier: 3,
      terms: ['komedia klasyczna', 'typ literacki', 'jedności dramatyczne'] },
    { id: 'krasicki',     title: 'Satyry — Krasicki',         branch: 'lektury', tier: 3,
      terms: ['satyra', 'ironia', 'dydaktyzm', 'bajka', 'parodia'] },

    // ── LEKTURY: Romantyzm ──
    { id: 'ballady',      title: 'Ballady / Romantyczność',   branch: 'lektury', tier: 4,
      terms: ['ballada', 'ludowość', 'fantastyka', 'dualizm', 'irracjonalizm'] },
    { id: 'dziady-iii',   title: 'Dziady cz. III',            branch: 'lektury', tier: 4,
      terms: ['prometeizm', 'mesjanizm', 'improwizacja', 'martyrologia', 'widzenie', 'profetyzm'] },

    // ── LEKTURY: Pozytywizm ──
    { id: 'lalka',        title: 'Lalka — Prus',              branch: 'lektury', tier: 5,
      terms: ['realizm', 'narracja wszechwiedzaca', 'idealizm', 'pozytywizm', 'emancypacja'] },
    { id: 'potop',        title: 'Potop — Sienkiewicz (fr.)', branch: 'lektury', tier: 5,
      terms: ['powieść historyczna', 'ku pokrzepieniu serc', 'sarmatyzm'] },
    { id: 'zbrodnia',     title: 'Zbrodnia i kara — Dostojewski', branch: 'lektury', tier: 5,
      terms: ['nihilizm', 'nadczłowiek', 'monolog wewnętrzny', 'ekspijacja', 'psychologizm'] },

    // ── LEKTURY: Młoda Polska ──
    { id: 'wesele',       title: 'Wesele — Wyspiański',       branch: 'lektury', tier: 6,
      terms: ['symbol', 'chocholi taniec', 'dramat symboliczny', 'złoty róg', 'marazm'] },
    { id: 'chlopi',       title: 'Chłopi — Reymont (fr.)',    branch: 'lektury', tier: 6,
      terms: ['naturalizm', 'epopeja', 'cykliczność', 'stylizacja gwarowa'] },

    // ── LEKTURY: Dwudziestolecie ──
    { id: 'przedwiosnie', title: 'Przedwiośnie — Żeromski',   branch: 'lektury', tier: 7,
      terms: ['utopia', 'szklane domy', 'rewolucja', 'dezynwoltura'] },
    { id: 'ferdydurke',   title: 'Ferdydurke — Gombrowicz',   branch: 'lektury', tier: 7,
      terms: ['forma', 'gęba', 'pupa', 'niedojrzałość', 'groteska', 'parodia'] },

    // ── LEKTURY: II wojna ──
    { id: 'borowski',     title: 'Proszę państwa do gazu — Borowski', branch: 'lektury', tier: 8,
      terms: ['człowiek zlagrowany', 'behawioryzm', 'narrator-uczestnik', 'dehumanizacja'] },
    { id: 'inny-swiat',   title: 'Inny świat — Herling-Grudziński',  branch: 'lektury', tier: 8,
      terms: ['łagier', 'totalitaryzm', 'literatura świadectwa', 'kondycja ludzka'] },
    { id: 'krall',        title: 'Zdążyć przed Panem Bogiem — Krall', branch: 'lektury', tier: 8,
      terms: ['reportaż', 'wywiad-rzeka', 'Zagłada', 'getto'] },

    // ── LEKTURY: Współczesność ──
    { id: 'dzuma',        title: 'Dżuma — Camus',             branch: 'lektury', tier: 9,
      terms: ['egzystencjalizm', 'absurd', 'alegoria', 'bunt', 'solidarność'] },
    { id: 'rok-1984',     title: 'Rok 1984 — Orwell',         branch: 'lektury', tier: 9,
      terms: ['dystopia', 'nowomowa', 'Wielki Brat', 'totalitaryzm', 'propaganda'] },
    { id: 'tango',        title: 'Tango — Mrożek',            branch: 'lektury', tier: 9,
      terms: ['groteska', 'absurd', 'konwencja', 'anarchia', 'autorytaryzm'] },
    { id: 'nowakowski',   title: 'Górą "Edek" — Nowakowski',  branch: 'lektury', tier: 9,
      terms: ['transformacja', 'prymitywizm', 'brutalizacja'] },
    { id: 'stasiuk',      title: 'Miejsce — Stasiuk',         branch: 'lektury', tier: 9,
      terms: ['małe ojczyzny', 'prowincja', 'egzystencja'] },
    { id: 'tokarczuk',    title: 'Profesor Andrews — Tokarczuk', branch: 'lektury', tier: 9,
      terms: ['obcość', 'wykluczenie', 'stereotyp', 'inność'] },
    { id: 'kapuscinski',  title: 'Podróże z Herodotem — Kapuściński', branch: 'lektury', tier: 9,
      terms: ['reportaż', 'interkulturowość', 'narracja podróżnicza'] },

    // ── MOTYWY ──
    { id: 'm-bunt',        title: 'Bunt i wolność',           branch: 'motywy', tier: 0,
      description: 'Antygona → Konrad → Cezary Baryka → Winston Smith',
      terms: ['prometeizm', 'nonkonformizm', 'rewolucja', 'opór'] },
    { id: 'm-cierpienie',  title: 'Cierpienie i śmierć',     branch: 'motywy', tier: 1,
      description: 'Hiob → Lament → Borowski → Inny świat',
      terms: ['teodyce', 'compassio', 'martyrologia', 'dehumanizacja'] },
    { id: 'm-moralnosc',   title: 'Wybór moralny',           branch: 'motywy', tier: 2,
      description: 'Antygona → Makbet → Raskolnikow → Dżuma',
      terms: ['dylemat etyczny', 'sumienie', 'ekspijacja', 'imperatyw'] },
    { id: 'm-patriotyzm',  title: 'Patriotyzm i tożsamość',  branch: 'motywy', tier: 4,
      description: 'Roland → Konrad → Kmicic → Wesele → Przedwiośnie',
      terms: ['mesjanizm', 'martyrologia', 'emigracja', 'irredenta'] },
    { id: 'm-spoleczenstwo', title: 'Klasy i nierówność',    branch: 'motywy', tier: 5,
      description: 'Skąpiec → Lalka → Chłopi → Ferdydurke',
      terms: ['stratyfikacja', 'emancypacja', 'arywista', 'mieszczaństwo'] },
    { id: 'm-forma',       title: 'Forma i konwenans',        branch: 'motywy', tier: 7,
      description: 'Gombrowicz: "gęba", niedojrzałość, pupa',
      terms: ['forma', 'konwencja', 'autentyczność', 'niedojrzałość'] },
    { id: 'm-totalitaryzm', title: 'Totalitaryzm i władza',  branch: 'motywy', tier: 8,
      description: 'Borowski → Herling → Orwell → Mrożek',
      terms: ['propaganda', 'nowomowa', 'totalitaryzm', 'konformizm'] },
    { id: 'm-obcosc',      title: 'Obcość i wykluczenie',     branch: 'motywy', tier: 9,
      description: 'Stasiuk → Tokarczuk → Nowakowski',
      terms: ['alienacja', 'stereotyp', 'marginalizacja', 'tożsamość'] },
    { id: 'm-prometeizm',  title: 'Prometeizm',               branch: 'motywy', tier: 4,
      description: 'Wielka Improwizacja — jednostka vs Bóg/system',
      terms: ['prometeizm', 'titanizm', 'indywidualizm', 'mesjanizm'] },
    { id: 'm-vanitas',     title: 'Vanitas / memento mori',   branch: 'motywy', tier: 1,
      description: 'Kohelet → Mistrz Polikarp → barokowa marność',
      terms: ['vanitas', 'memento mori', 'danse macabre', 'eschatologia'] },

    // ── GATUNKI ──
    { id: 'g-tragedia',    title: 'Tragedia antyczna',         branch: 'gatunki', tier: 0,
      terms: ['tragizm', 'katharsis', 'hamartia', 'perypetia', 'anagnorisis'] },
    { id: 'g-epos',        title: 'Epos',                      branch: 'gatunki', tier: 0,
      terms: ['inwokacja', 'heksametr', 'epitheton ornans', 'narrator epicki'] },
    { id: 'g-dramat',      title: 'Dramat',                    branch: 'gatunki', tier: 2,
      description: 'Szekspir → Molier → Wyspiański → Mrożek',
      terms: ['akt', 'scena', 'didaskalia', 'monolog', 'dialog', 'konflikt'] },
    { id: 'g-satyra',      title: 'Satyra',                    branch: 'gatunki', tier: 3,
      terms: ['ironia', 'sarkazm', 'parodia', 'karykatura'] },
    { id: 'g-ballada',     title: 'Ballada',                   branch: 'gatunki', tier: 4,
      terms: ['synkretyzm', 'ludowość', 'fantastyka', 'nastrój'] },
    { id: 'g-powiesc',     title: 'Powieść realistyczna',      branch: 'gatunki', tier: 5,
      terms: ['realizm', 'narrator', 'fabuła', 'wątek', 'psychologizm'] },
    { id: 'g-reportaz',    title: 'Reportaż / literatura faktu', branch: 'gatunki', tier: 8,
      terms: ['reportaż', 'fakt', 'fikcja', 'narracja dziennikarska'] },
    { id: 'g-groteska',    title: 'Groteska',                  branch: 'gatunki', tier: 7,
      terms: ['groteska', 'absurd', 'deformacja', 'hiperbola', 'parodia'] },
    { id: 'g-opowiadanie', title: 'Opowiadanie współczesne',   branch: 'gatunki', tier: 9,
      terms: ['miniatura', 'puenta', 'epifania', 'narracja pierwszoosobowa'] },

    // ── WARSZTAT ──
    { id: 'w-ironia',      title: 'Ironia i satyra',           branch: 'warsztat', tier: 3,
      terms: ['ironia', 'sarkazm', 'antyteza', 'hiperbola', 'eufemizm'] },
    { id: 'w-monolog',     title: 'Monolog dramatyczny',       branch: 'warsztat', tier: 4,
      description: 'Wielka Improwizacja, monolog Makbeta',
      terms: ['monolog', 'solilokwium', 'apostrofa', 'inwokacja'] },
    { id: 'w-realizm',     title: 'Realizm / naturalizm',      branch: 'warsztat', tier: 5,
      terms: ['mimesis', 'determinizm', 'detal realistyczny', 'typowość'] },
    { id: 'w-symbol',      title: 'Symbol i alegoria',         branch: 'warsztat', tier: 6,
      description: 'Wesele: Chochoł, złoty róg; Dżuma: zaraza jako...',
      terms: ['symbol', 'alegoria', 'metafora', 'metonimia', 'synekdocha'] },
    { id: 'w-groteska',    title: 'Groteska literacka',        branch: 'warsztat', tier: 7,
      description: 'Gombrowicz, Mrożek — deformacja, absurd, gęba',
      terms: ['groteska', 'absurd', 'parodia', 'karykatura', 'konwencja'] },
    { id: 'w-narracja',    title: 'Punkt widzenia / narracja', branch: 'warsztat', tier: 8,
      description: 'Borowski (narrator-uczestnik), Krall (wywiad-rzeka)',
      terms: ['narracja', 'fokalizacja', 'narrator', 'perspektywa', 'strumień świadomości'] },
    { id: 'w-rozprawka',   title: 'Rozprawka maturalna',       branch: 'warsztat', tier: 9,
      description: 'Teza, argumenty, konteksty, wnioski',
      terms: ['teza', 'argument', 'kontrargument', 'kontekst interpretacyjny', 'wniosek'] },

    // ── BRIDGE ──
    { id: 'br-mit',        title: 'Mitologia a kultura',       branch: 'bridge', tier: 0,
      bridgeTo: 'Historia sztuki', description: '→ Archetypy, symbole w malarstwie i rzeźbie' },
    { id: 'br-antyk-fil',  title: 'Etyka antyczna',            branch: 'bridge', tier: 0,
      bridgeTo: 'Filozofia', description: '→ Prawo boskie vs ludzkie, hybris, fatum' },
    { id: 'br-feudalizm',  title: 'Feudalizm i rycerstwo',     branch: 'bridge', tier: 1,
      bridgeTo: 'Historia', description: '→ Krucjaty, system feudalny, honor' },
    { id: 'br-humanizm',   title: 'Humanizm renesansowy',      branch: 'bridge', tier: 2,
      bridgeTo: 'Filozofia', description: '→ Antropocentryzm, reforma, Makiawelizm' },
    { id: 'br-oswiecenie',  title: 'Racjonalizm i rewolucja', branch: 'bridge', tier: 3,
      bridgeTo: 'Historia', description: '→ Rewolucja Francuska, Konstytucja 3 maja' },
    { id: 'br-powstania',  title: 'Powstania i emigracja',     branch: 'bridge', tier: 4,
      bridgeTo: 'Historia', description: '→ Powstanie listopadowe, Wielka Emigracja' },
    { id: 'br-rewolucja',  title: 'Rewolucja przemysłowa',     branch: 'bridge', tier: 5,
      bridgeTo: 'Historia', description: '→ Industrializacja, nowe klasy, kapitalizm' },
    { id: 'br-niepodleglosc', title: 'Odzyskanie niepodległości', branch: 'bridge', tier: 7,
      bridgeTo: 'Historia', description: '→ 1918, wizje Polski, lewica vs prawica' },
    { id: 'br-holocaust',  title: 'Zagłada i pamięć',          branch: 'bridge', tier: 8,
      bridgeTo: 'Historia', description: '→ Auschwitz, getto, Sprawiedliwi' },
    { id: 'br-egzyst',     title: 'Egzystencjalizm',           branch: 'bridge', tier: 9,
      bridgeTo: 'Filozofia', description: '→ Camus, Sartre, absurd, wolność wyboru' },
    { id: 'br-totali',     title: 'Systemy totalitarne',       branch: 'bridge', tier: 9,
      bridgeTo: 'WOS / Historia', description: '→ Nazizm, stalinizm, propaganda, PRL' },
  ],

  edges: [
    // ── Kręgosłup: epoki ──
    { from: 'antyk',            to: 'sredniowiecze',   type: 'progression' },
    { from: 'sredniowiecze',   to: 'renesans',         type: 'progression' },
    { from: 'renesans',        to: 'oswiecenie',       type: 'progression' },
    { from: 'oswiecenie',      to: 'romantyzm',        type: 'progression' },
    { from: 'romantyzm',       to: 'pozytywizm',       type: 'progression' },
    { from: 'pozytywizm',      to: 'modernizm',        type: 'progression' },
    { from: 'modernizm',       to: 'dwudziestolecie',  type: 'progression' },
    { from: 'dwudziestolecie', to: 'ii-wojna',         type: 'progression' },
    { from: 'ii-wojna',        to: 'wspolczesnosc',    type: 'progression' },

    // ── Epoki → Lektury ──
    { from: 'antyk',            to: 'biblia',       type: 'branch' },
    { from: 'antyk',            to: 'mitologia',    type: 'branch' },
    { from: 'antyk',            to: 'iliada',       type: 'branch' },
    { from: 'antyk',            to: 'antygona',     type: 'branch' },
    { from: 'sredniowiecze',   to: 'lament',        type: 'branch' },
    { from: 'sredniowiecze',   to: 'polikarp',      type: 'branch' },
    { from: 'sredniowiecze',   to: 'roland',        type: 'branch' },
    { from: 'renesans',        to: 'makbet',        type: 'branch' },
    { from: 'oswiecenie',      to: 'skapiec',       type: 'branch' },
    { from: 'oswiecenie',      to: 'krasicki',      type: 'branch' },
    { from: 'romantyzm',       to: 'ballady',       type: 'branch' },
    { from: 'romantyzm',       to: 'dziady-iii',    type: 'branch' },
    { from: 'pozytywizm',      to: 'lalka',         type: 'branch' },
    { from: 'pozytywizm',      to: 'potop',         type: 'branch' },
    { from: 'pozytywizm',      to: 'zbrodnia',      type: 'branch' },
    { from: 'modernizm',       to: 'wesele',        type: 'branch' },
    { from: 'modernizm',       to: 'chlopi',        type: 'branch' },
    { from: 'dwudziestolecie', to: 'przedwiosnie',  type: 'branch' },
    { from: 'dwudziestolecie', to: 'ferdydurke',    type: 'branch' },
    { from: 'ii-wojna',        to: 'borowski',      type: 'branch' },
    { from: 'ii-wojna',        to: 'inny-swiat',    type: 'branch' },
    { from: 'ii-wojna',        to: 'krall',         type: 'branch' },
    { from: 'wspolczesnosc',   to: 'dzuma',         type: 'branch' },
    { from: 'wspolczesnosc',   to: 'rok-1984',      type: 'branch' },
    { from: 'wspolczesnosc',   to: 'tango',         type: 'branch' },
    { from: 'wspolczesnosc',   to: 'nowakowski',    type: 'branch' },
    { from: 'wspolczesnosc',   to: 'stasiuk',       type: 'branch' },
    { from: 'wspolczesnosc',   to: 'tokarczuk',     type: 'branch' },
    { from: 'wspolczesnosc',   to: 'kapuscinski',   type: 'branch' },

    // ── Lektury → Motywy ──
    { from: 'antygona',     to: 'm-bunt',        type: 'branch' },
    { from: 'dziady-iii',   to: 'm-bunt',        type: 'branch' },
    { from: 'przedwiosnie', to: 'm-bunt',        type: 'branch' },
    { from: 'rok-1984',     to: 'm-bunt',        type: 'branch' },
    { from: 'biblia',       to: 'm-cierpienie',  type: 'branch' },
    { from: 'lament',       to: 'm-cierpienie',  type: 'branch' },
    { from: 'borowski',     to: 'm-cierpienie',  type: 'branch' },
    { from: 'inny-swiat',   to: 'm-cierpienie',  type: 'branch' },
    { from: 'antygona',     to: 'm-moralnosc',   type: 'branch' },
    { from: 'makbet',       to: 'm-moralnosc',   type: 'branch' },
    { from: 'zbrodnia',     to: 'm-moralnosc',   type: 'branch' },
    { from: 'dzuma',        to: 'm-moralnosc',   type: 'branch' },
    { from: 'roland',       to: 'm-patriotyzm',  type: 'branch' },
    { from: 'dziady-iii',   to: 'm-patriotyzm',  type: 'branch' },
    { from: 'potop',        to: 'm-patriotyzm',  type: 'branch' },
    { from: 'wesele',       to: 'm-patriotyzm',  type: 'branch' },
    { from: 'skapiec',      to: 'm-spoleczenstwo', type: 'branch' },
    { from: 'lalka',        to: 'm-spoleczenstwo', type: 'branch' },
    { from: 'chlopi',       to: 'm-spoleczenstwo', type: 'branch' },
    { from: 'ferdydurke',   to: 'm-forma',       type: 'branch' },
    { from: 'tango',        to: 'm-forma',       type: 'branch' },
    { from: 'borowski',     to: 'm-totalitaryzm', type: 'branch' },
    { from: 'inny-swiat',   to: 'm-totalitaryzm', type: 'branch' },
    { from: 'rok-1984',     to: 'm-totalitaryzm', type: 'branch' },
    { from: 'nowakowski',   to: 'm-obcosc',      type: 'branch' },
    { from: 'stasiuk',      to: 'm-obcosc',      type: 'branch' },
    { from: 'tokarczuk',    to: 'm-obcosc',      type: 'branch' },
    { from: 'dziady-iii',   to: 'm-prometeizm',  type: 'branch' },
    { from: 'polikarp',     to: 'm-vanitas',     type: 'branch' },
    { from: 'biblia',       to: 'm-vanitas',     type: 'branch' },

    // ── Lektury → Gatunki ──
    { from: 'antygona',     to: 'g-tragedia',    type: 'branch' },
    { from: 'iliada',       to: 'g-epos',        type: 'branch' },
    { from: 'roland',       to: 'g-epos',        type: 'branch' },
    { from: 'makbet',       to: 'g-dramat',      type: 'branch' },
    { from: 'skapiec',      to: 'g-dramat',      type: 'branch' },
    { from: 'wesele',       to: 'g-dramat',      type: 'branch' },
    { from: 'tango',        to: 'g-dramat',      type: 'branch' },
    { from: 'krasicki',     to: 'g-satyra',      type: 'branch' },
    { from: 'ballady',      to: 'g-ballada',     type: 'branch' },
    { from: 'lalka',        to: 'g-powiesc',     type: 'branch' },
    { from: 'zbrodnia',     to: 'g-powiesc',     type: 'branch' },
    { from: 'chlopi',       to: 'g-powiesc',     type: 'branch' },
    { from: 'krall',        to: 'g-reportaz',    type: 'branch' },
    { from: 'kapuscinski',  to: 'g-reportaz',    type: 'branch' },
    { from: 'ferdydurke',   to: 'g-groteska',    type: 'branch' },
    { from: 'tango',        to: 'g-groteska',    type: 'branch' },
    { from: 'nowakowski',   to: 'g-opowiadanie', type: 'branch' },
    { from: 'stasiuk',      to: 'g-opowiadanie', type: 'branch' },
    { from: 'tokarczuk',    to: 'g-opowiadanie', type: 'branch' },

    // ── Warsztat ──
    { from: 'krasicki',     to: 'w-ironia',      type: 'branch' },
    { from: 'g-satyra',     to: 'w-ironia',      type: 'branch' },
    { from: 'dziady-iii',   to: 'w-monolog',     type: 'branch' },
    { from: 'makbet',       to: 'w-monolog',     type: 'branch' },
    { from: 'lalka',        to: 'w-realizm',     type: 'branch' },
    { from: 'chlopi',       to: 'w-realizm',     type: 'branch' },
    { from: 'wesele',       to: 'w-symbol',      type: 'branch' },
    { from: 'dzuma',        to: 'w-symbol',      type: 'branch' },
    { from: 'ferdydurke',   to: 'w-groteska',    type: 'branch' },
    { from: 'tango',        to: 'w-groteska',    type: 'branch' },
    { from: 'borowski',     to: 'w-narracja',    type: 'branch' },
    { from: 'krall',        to: 'w-narracja',    type: 'branch' },
    { from: 'm-moralnosc',  to: 'w-rozprawka',   type: 'branch' },
    { from: 'm-bunt',       to: 'w-rozprawka',   type: 'branch' },

    // ── Mosty międzyprzedmiotowe ──
    { from: 'mitologia',    to: 'br-mit',        type: 'bridge' },
    { from: 'antygona',     to: 'br-antyk-fil',  type: 'bridge' },
    { from: 'm-moralnosc',  to: 'br-antyk-fil',  type: 'bridge' },
    { from: 'roland',       to: 'br-feudalizm',  type: 'bridge' },
    { from: 'makbet',       to: 'br-humanizm',   type: 'bridge' },
    { from: 'krasicki',     to: 'br-oswiecenie', type: 'bridge' },
    { from: 'skapiec',      to: 'br-oswiecenie', type: 'bridge' },
    { from: 'dziady-iii',   to: 'br-powstania',  type: 'bridge' },
    { from: 'm-patriotyzm', to: 'br-powstania',  type: 'bridge' },
    { from: 'lalka',        to: 'br-rewolucja',  type: 'bridge' },
    { from: 'm-spoleczenstwo', to: 'br-rewolucja', type: 'bridge' },
    { from: 'przedwiosnie', to: 'br-niepodleglosc', type: 'bridge' },
    { from: 'wesele',       to: 'br-niepodleglosc', type: 'bridge' },
    { from: 'borowski',     to: 'br-holocaust',  type: 'bridge' },
    { from: 'krall',        to: 'br-holocaust',  type: 'bridge' },
    { from: 'inny-swiat',   to: 'br-holocaust',  type: 'bridge' },
    { from: 'dzuma',        to: 'br-egzyst',     type: 'bridge' },
    { from: 'rok-1984',     to: 'br-totali',     type: 'bridge' },
    { from: 'm-totalitaryzm', to: 'br-totali',   type: 'bridge' },
  ],
}

export default polskiMatura
